import { useCallback, useEffect, useState } from 'react'

/**
 * The market, refreshed on a timer.
 *
 * Until the first real ingestion run has published, or when the API is
 * unreachable, this falls back to the mock market — which is generated by the
 * real scoring engine over invented counts, carries `mock: true`, and is
 * announced on screen. Real and fake never blend silently.
 */
export function useMarket(refreshMs = 60000) {
  const [market, setMarket] = useState(null)
  const [error, setError] = useState(null)

  const load = useCallback(async () => {
    try {
      const res = await fetch('/api/market', { cache: 'no-store' })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const data = await res.json()
      if (!data?.rows?.length) throw new Error('empty market')
      setMarket(data); setError(null)
    } catch (err) {
      setError(err.message)
      const { mockMarket } = await import('../../market/mock.mjs')
      setMarket((m) => (m && !m.mock ? m : mockMarket({ now: Date.now() })))
    }
  }, [])

  useEffect(() => {
    load()
    const t = setInterval(load, refreshMs)
    return () => clearInterval(t)
  }, [load, refreshMs])

  return { market, error, reload: load }
}

/** "4 minutes ago" / "3 hours ago", for freshness labels that must be honest. */
export function sinceLabel(seconds) {
  if (!Number.isFinite(seconds)) return 'unknown'
  const s = Math.max(0, Math.round(seconds))
  if (s < 90) return `${s}s ago`
  const m = Math.round(s / 60)
  if (m < 90) return `${m} min ago`
  const h = Math.round(m / 60)
  if (h < 36) return `${h} hour${h === 1 ? '' : 's'} ago`
  return `${Math.round(h / 24)} days ago`
}

export const signed = (n, dp = 2) =>
  (n == null || !Number.isFinite(n)) ? '—' : `${n > 0 ? '+' : ''}${n.toFixed(dp)}`

export const dirOf = (n) => (n == null || !Number.isFinite(n) ? 'flat' : n > 0.05 ? 'up' : n < -0.05 ? 'down' : 'flat')
